// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqq77Ll-80fC52Xqe_VEmi1bUX8HStlzU',
    appId: '1:896547519626:web:8944a8fa38fd29d92d8173',
    messagingSenderId: '896547519626',
    projectId: 'syncup-f1a48',
    authDomain: 'syncup-f1a48.firebaseapp.com',
    storageBucket: 'syncup-f1a48.appspot.com',
    measurementId: 'G-LQT6KQ8W44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTuf2wmwDJtKrE2G3AGgfY7dV0AC6mFJk',
    appId: '1:896547519626:android:6196e5d226596acb2d8173',
    messagingSenderId: '896547519626',
    projectId: 'syncup-f1a48',
    storageBucket: 'syncup-f1a48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPDkAYdb3ibso9-XsQ3k5oDddzbr6bFW8',
    appId: '1:896547519626:ios:cba85139e39355c72d8173',
    messagingSenderId: '896547519626',
    projectId: 'syncup-f1a48',
    storageBucket: 'syncup-f1a48.appspot.com',
    iosBundleId: 'com.example.projectSyncup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPDkAYdb3ibso9-XsQ3k5oDddzbr6bFW8',
    appId: '1:896547519626:ios:cba85139e39355c72d8173',
    messagingSenderId: '896547519626',
    projectId: 'syncup-f1a48',
    storageBucket: 'syncup-f1a48.appspot.com',
    iosBundleId: 'com.example.projectSyncup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqq77Ll-80fC52Xqe_VEmi1bUX8HStlzU',
    appId: '1:896547519626:web:b9074c0739dae9fb2d8173',
    messagingSenderId: '896547519626',
    projectId: 'syncup-f1a48',
    authDomain: 'syncup-f1a48.firebaseapp.com',
    storageBucket: 'syncup-f1a48.appspot.com',
    measurementId: 'G-NVCFZNK3HW',
  );

}